name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This is a issue PR. If there isn't any activity this issue may be closed. Thanks for contributing to wgytcraft."
        stale-pr-message: "This is a stale PR. If there isn't any activity this issue may be closed. Thanks for contributing to wgytcraft."
        stale-issue-label: 'status: stale'
        stale-pr-label: 'status: stale'
